name: Update develop after master merge

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  develop_update:
    runs-on: ubuntu-latest

    if: |
      github.repository == 'drashna/qmk_userspace' && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_BOT_SECRET }}
        fetch-depth: 0

    - name: Disable automatic eol conversion
      run: |
        echo "* -text" > .git/info/attributes

    - name: Checkout develop
      run: |
        git fetch origin master develop
        git checkout develop

    - name: Update develop from master
      id: update
      run: |
        git config --global user.name "Drashna Bot"
        git config user.email drashna@live.com
        git rebase origin/master

    - name: Create Pull Request
      if: steps.update.conclusion == 'failure'
      run: |
        git rebase --abort
        gh pr create -B develop -H master --title 'Manually update develop branch after master merge' --body 'Created by Github action'

    - name: Push updates to develop
      if: steps.update.conclusion != 'failure'
      run: |
        git push origin develop --force-with-lease
